name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  AWS_S3_BUCKET: "rocketseat-upload-widget-web-static-yang"
  SOURCE_DIST: ./dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install-dependencies
        run: npm install

      - name: Build App
        id: build-app
        run: npm run build

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{vars.AWS_REGION}}

      - name: Sync files do S3
        id: sync-files-to-s3
        run: |
          aws s3 sync ${{env.SOURCE_DIST}} s3://${{env.AWS_S3_BUCKET}}/ --delete
